const axios = require("axios")
const fs = require("fs")
const path = require("path")
const { BASE_URL, TOTAL_VIDEOS } = require("../config")

const tokens = Object.values(
  JSON.parse(fs.readFileSync("./data/tokens.json", "utf-8"))
)

const sampleFilePath = path.join(__dirname, "sample.mp4")
const sampleBuffer = fs.readFileSync(sampleFilePath)

const randomToken = () =>
  tokens[Math.floor(Math.random() * tokens.length)]

const run = async () => {
  for (let i = 1; i <= 2; i++) {
    const token = randomToken()

    try {
      // 1️⃣ INIT UPLOAD
      const initRes = await axios.post(
        `${BASE_URL}/api/videos/upload/init`,
        {
          title: `Auto Video ${i}`,
          description: "Generated by load test",
          fileSize: sampleBuffer.length,
          mimeType: "video/mp4",
          originalName: "sample.mp4",
        },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      )

      const { videoId, uploadUrl } = initRes.data

      // 2️⃣ UPLOAD FILE TO S3 (THIS WAS MISSING)
      await axios.put(uploadUrl, sampleBuffer, {
        headers: {
          "Content-Type": "video/mp4",
          "Content-Length": sampleBuffer.length,
        },
        maxBodyLength: Infinity,
        maxContentLength: Infinity,
      })
      // 3️⃣ COMPLETE UPLOAD
      await axios.post(
        `${BASE_URL}/api/videos/upload/complete`,
        { videoId },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      )
// ADD THIS DEBUG CHECK
console.log(`🔍 Checking if video ${i} exists in DB...`);
await new Promise(r => setTimeout(r, 1000)); // Wait 1 second

console.log(`🎬 Uploaded video ${i}`);
      console.log(`🎬 Uploaded video ${i}`)
    } catch (err) {
      console.log(`❌ Upload failed ${i}`)
      console.log(err.response?.data || err.message)
    }
  }

  console.log("🎉 Upload script finished")
}

run()
